base:
  batch_size: 32
  checkpoint_interval: 50
  decay_every: 20
  decay_rate: 0.9
  epochs: 200
  lambda_cos: 10
  lambda_l1: 1
  lambda_reg: 0
  lambda_vae: 3
  learning_rate: 5.e-8
incr:
  batch_size: 32
  checkpoint_interval: 25
  decay_every: 10
  decay_rate: 0.9
  epochs: 100
  lambda_cos: 10
  lambda_l1: 1
  lambda_reg: 20
  lambda_vae: 3
  learning_rate: 5.e-8
log_interval: 17
seed: 86