log_interval: 17
seed: 86
base:
  epochs: 200
  batch_size: 32
  learning_rate: 0.00000005
  decay_rate: 0.9
  decay_every: 20 # epochs
  lambda_l1: 1
  lambda_vae: 3
  lambda_cos: 10
  lambda_reg: 0
  checkpoint_interval: 50
incr:
  epochs: 100
  batch_size: 32
  learning_rate: 0.00000005
  decay_rate: 0.9
  decay_every: 10 # epochs
  lambda_l1: 1
  lambda_vae: 3
  lambda_cos: 10
  lambda_reg: 20
  checkpoint_interval: 25
