base:
  batch_multiplier: 1
  batch_size: 32
  checkpoint_interval: 50
  decay_every: 50
  decay_rate: 1
  epochs: 100
  lambda_cos: 10
  lambda_l1: 0
  lambda_reg: 0
  lambda_vae: 5
  learning_rate: 0.0001
  optimizer: adam
incr:
  batch_multiplier: 1
  batch_size: 32
  checkpoint_interval: 25
  decay_every: 25
  decay_rate: 0.9
  epochs: 50
  lambda_cos: 10
  lambda_l1: 0
  lambda_reg: 20
  lambda_vae: 5
  learning_rate: 0.0001
  optimizer: adam
vae:
  enc:
    - 8192
    - 6144 
    - 3072
    - 2048
  dec:
    - 2048 
    - 3072
    - 6144
    - 8192
log_interval: 17
rho: 0.8
seed: 86
