augmentate: false
base:
  batch_multiplier: 1
  batch_size: 32
  checkpoint_interval: 50
  decay_every: 50
  decay_rate: 1
  epochs: 100
  lambda_cos: 10
  lambda_l1: 0
  lambda_reg: 0
  lambda_vae: 1
  learning_rate: 1e-05
  optimizer: adam
incr:
  batch_multiplier: 1
  batch_size: 32
  checkpoint_interval: 25
  decay_every: 25
  decay_rate: 0.9
  epochs: 10
  lambda_cos: 10
  lambda_l1: 0
  lambda_reg: 20
  lambda_vae: 1
  learning_rate: 1e-05
  optimizer: adam
log_interval: 17
rho: 0.8
seed: 86
vae:
  dec:
  - 2048
  - 4096
  - 8192
  enc:
  - 8192
  - 4096
  - 2048
