log_interval: 17
seed: 33
base:
  epochs: 250
  batch_size: 32
  learning_rate: 0.000002
  decay_rate: 0.9
  decay_every: 50 # epochs
  lambda_vae: 1
  lambda_cos: 10
  lambda_reg: 0
  checkpoint_interval: 50
incr:
  epochs: 125
  batch_size: 32
  learning_rate: 0.000002
  decay_rate: 0.8
  decay_every: 25 # epochs
  lambda_vae: 1
  lambda_cos: 5
  lambda_reg: 10
  checkpoint_interval: 25