log_interval: 17
seed: 15
base:
  epochs: 250
  batch_size: 32
  learning_rate: 0.000005
  decay_rate: 0.85 
  decay_every: 50 # epochs
  lambda_vae: 1
  lambda_cos: 20
  lambda_reg: 0
  checkpoint_interval: 50
incr:
  epochs: 125
  batch_size: 32
  learning_rate: 0.0000035
  decay_rate: 0.8
  decay_every: 25 # epochs
  lambda_vae: 1
  lambda_cos: 10
  lambda_reg: 20
  checkpoint_interval: 25