log_interval: 50
seed: 10
base:
  epochs: 100
  batch_size: 16
  learning_rate: 0.000004
  decay_rate: 0.9 
  decay_every: 20 # epochs
  lambda_vae: 1
  lambda_cos: 10
  lambda_reg: 0
incr:
  epochs: 50
  batch_size: 16
  learning_rate: 0.000004
  decay_rate: 1.0
  decay_every: 20 # epochs
  lambda_vae: 1
  lambda_cos: 10
  lambda_reg: 10