log_interval: 50
seed: 15
base:
  epochs: 150
  batch_size: 16
  learning_rate: 0.0000045
  decay_rate: 0.95 
  decay_every: 30 # epochs
  lambda_vae: 1
  lambda_cos: 15
  lambda_reg: 0
incr:
  epochs: 50
  batch_size: 16
  learning_rate: 0.000004
  decay_rate: 1.0
  decay_every: 20 # epochs
  lambda_vae: 1
  lambda_cos: 10
  lambda_reg: 10